theme: jekyll-theme-cayman
title: Czech Pair Travel
description: We are a couple from Czech Republic. We love to travel, drink, eat, meet new people and generally try to enjoy life as much as we can:)
twitter_username: czechpairtravel

author:
  name:       Marťa & Vašek
  url:        http://czechpairtravel.com

github:
  is_project_page: false